In [78]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [79]:
data=pd.read_csv("/content/coviddeath.csv")
data

,Data as of,Start Week,End Week,State,Condition Group,Condition,ICD10_codes,Age Group,Number of COVID-19 Deaths,Flag
0,08/30/2020,02/01/2020,08/29/2020,US,Respiratory diseases,Influenza and pneumonia,J09-J18,0-24,122.0,NaN
1,08/30/2020,02/01/2020,08/29/2020,US,Respiratory diseases,Influenza and pneumonia,J09-J18,25-34,596.0,NaN
2,08/30/2020,02/01/2020,08/29/2020,US,Respiratory diseases,Influenza and pneumonia,J09-J18,35-44,1521.0,NaN
3,08/30/2020,02/01/2020,08/29/2020,US,Respiratory diseases,Influenza and pneumonia,J09-J18,45-54,4186.0,NaN
4,08/30/2020,02/01/2020,08/29/2020,US,Respiratory diseases,Influenza and pneumonia,J09-J18,55-64,10014.0,NaN
...,...,...,...,...,...,...,...,...,...,...
12255,08/30/2020,02/01/2020,08/29/2020,YC,Coronavirus Disease 2019,COVID-19,U071,65-74,5024.0,NaN
12256,08/30/2020,02/01/2020,08/29/2020,YC,Coronavirus Disease 2019,COVID-19,U071,75-84,5381.0,NaN
12257,08/30/2020,02/01/2020,08/29/2020,YC,Coronavirus Disease 2019,COVID-19,U071,85+,4841.0,NaN
12258,08/30/2020,02/01/2020,08/29/2020,YC,Coronavirus Disease 2019,COVID-19,U071,Not stated,NaN,Counts less than 10 suppressed.
12259,08/30/2020,02/01/2020,08/29/2020,YC,Coronavirus Disease 2019,COVID-19,U071,All ages,20628.0,NaN

In [80]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12260 entries, 0 to 12259
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Data as of                 12260 non-null  object
 1   Start Week                 12260 non-null  object
 2   End Week                   12260 non-null  object
 3   State                      12260 non-null  object
 4   Condition Group            12260 non-null  object
 5   Condition                  12260 non-null  object
 6   ICD10_codes                12260 non-null  object
 7   Age Group                  12260 non-null  object
 8   Number of COVID-19 Deaths  5354 non-null   float64
 9   Flag                       6906 non-null   object
dtypes: float64(1), object(9)
memory usage: 957.9+ KB

In [81]:
data.describe()

       Number of COVID-19 Deaths
count                5354.000000
mean                  479.861225
std                  3411.685320
min                     0.000000
25%                    24.000000
50%                    62.000000
75%                   196.000000
max                169044.000000

In [82]:

data['Data as of'] = pd.to_datetime(data['Data as of'])
data['Start Week'] = pd.to_datetime(data['Start Week'])
data['End Week'] = pd.to_datetime(data['End Week'])

text_columns = ['State', 'Condition Group', 'Condition', 'ICD10_codes']
data[text_columns] = data[text_columns].astype(str)

In [84]:
data[['Data as of','Start Week','End Week']].nunique()

Data as of    1
Start Week    1
End Week      1
dtype: int64

In [86]:
data = data.drop(['Data as of','Start Week','End Week'], axis=1)

In [87]:
data.duplicated().sum()

np.int64(0)

In [88]:
data.shape

(12260, 7)

In [89]:
data.isnull().sum()

State                           0
Condition Group                 0
Condition                       0
ICD10_codes                     0
Age Group                       0
Number of COVID-19 Deaths    6906
Flag                         5354
dtype: int64

In [90]:
data['Number of COVID-19 Deaths'] = data['Number of COVID-19 Deaths'].fillna(0)

In [91]:
data['Flag'] = data['Flag'].fillna('Unknown')

In [92]:
data['Number of COVID-19 Deaths'] = data['Number of COVID-19 Deaths'].astype(int)

In [93]:
data

,State,Condition Group,Condition,ICD10_codes,Age Group,Number of COVID-19 Deaths,Flag
0,US,Respiratory diseases,Influenza and pneumonia,J09-J18,0-24,122,Unknown
1,US,Respiratory diseases,Influenza and pneumonia,J09-J18,25-34,596,Unknown
2,US,Respiratory diseases,Influenza and pneumonia,J09-J18,35-44,1521,Unknown
3,US,Respiratory diseases,Influenza and pneumonia,J09-J18,45-54,4186,Unknown
4,US,Respiratory diseases,Influenza and pneumonia,J09-J18,55-64,10014,Unknown
...,...,...,...,...,...,...,...
12255,YC,Coronavirus Disease 2019,COVID-19,U071,65-74,5024,Unknown
12256,YC,Coronavirus Disease 2019,COVID-19,U071,75-84,5381,Unknown
12257,YC,Coronavirus Disease 2019,COVID-19,U071,85+,4841,Unknown
12258,YC,Coronavirus Disease 2019,COVID-19,U071,Not stated,0,Counts less than 10 suppressed.
12259,YC,Coronavirus Disease 2019,COVID-19,U071,All ages,20628,Unknown

In [94]:
data.groupby('Age Group')['Number of COVID-19 Deaths'].sum()

Age Group
0-24             1905
25-34            8248
35-44           23338
45-54           66189
55-64          163736
65-74          284286
75-84          343924
85+            387741
All ages      1289774
Not stated         36
Name: Number of COVID-19 Deaths, dtype: int64

In [95]:
data.groupby('Condition')['Number of COVID-19 Deaths'].mean()

Condition
Adult respiratory distress syndrome                                           167.418519
All other conditions and causes (residual)                                    609.790741
Alzheimer disease                                                              44.090566
COVID-19                                                                     1251.372222
Cardiac arrest                                                                160.646154
Cardiac arrhythmia                                                             76.109259
Cerebrovascular diseases                                                       60.011321
Chronic lower respiratory diseases                                            106.942593
Diabetes                                                                      203.020370
Heart failure                                                                  80.948148
Hypertensive diseases                                                         275.614815
Influenza and pneumonia                                                       530.350000
Intentional and unintentional injury, poisoning, and other adverse events      40.526923
Ischemic heart disease                                                        140.877778
Malignant neoplasms                                                            56.829630
Obesity                                                                        44.275472
Other diseases of the circulatory system                                       68.532075
Other diseases of the respiratory system                                       43.111111
Renal failure                                                                 106.529630
Respiratory arrest                                                             27.264583
Respiratory failure                                                           425.207407
Sepsis                                                                        111.592453
Vascular and unspecified dementia                                             145.939623
Name: Number of COVID-19 Deaths, dtype: float64

In [96]:
data = data[~data['Age Group'].isin(['All ages', 'Not stated'])]

In [97]:
age_map = {
    '0-24': 1,
    '25-34': 2,
    '35-44': 3,
    '45-54': 4,
    '55-64': 5,
    '65-74': 6,
    '75-84': 7,
    '85+': 8
}

data['Age_encoded'] = data['Age Group'].map(age_map)

/tmp/ipython-input-3678759421.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age_encoded'] = data['Age Group'].map(age_map)

In [98]:
data

,State,Condition Group,Condition,ICD10_codes,Age Group,Number of COVID-19 Deaths,Flag,Age_encoded
0,US,Respiratory diseases,Influenza and pneumonia,J09-J18,0-24,122,Unknown,1
1,US,Respiratory diseases,Influenza and pneumonia,J09-J18,25-34,596,Unknown,2
2,US,Respiratory diseases,Influenza and pneumonia,J09-J18,35-44,1521,Unknown,3
3,US,Respiratory diseases,Influenza and pneumonia,J09-J18,45-54,4186,Unknown,4
4,US,Respiratory diseases,Influenza and pneumonia,J09-J18,55-64,10014,Unknown,5
...,...,...,...,...,...,...,...,...
12253,YC,Coronavirus Disease 2019,COVID-19,U071,45-54,1379,Unknown,4
12254,YC,Coronavirus Disease 2019,COVID-19,U071,55-64,3272,Unknown,5
12255,YC,Coronavirus Disease 2019,COVID-19,U071,65-74,5024,Unknown,6
12256,YC,Coronavirus Disease 2019,COVID-19,U071,75-84,5381,Unknown,7
12257,YC,Coronavirus Disease 2019,COVID-19,U071,85+,4841,Unknown,8

In [99]:
data= data[data['State'] != 'YC']

In [100]:
data

,State,Condition Group,Condition,ICD10_codes,Age Group,Number of COVID-19 Deaths,Flag,Age_encoded
0,US,Respiratory diseases,Influenza and pneumonia,J09-J18,0-24,122,Unknown,1
1,US,Respiratory diseases,Influenza and pneumonia,J09-J18,25-34,596,Unknown,2
2,US,Respiratory diseases,Influenza and pneumonia,J09-J18,35-44,1521,Unknown,3
3,US,Respiratory diseases,Influenza and pneumonia,J09-J18,45-54,4186,Unknown,4
4,US,Respiratory diseases,Influenza and pneumonia,J09-J18,55-64,10014,Unknown,5
...,...,...,...,...,...,...,...,...
12023,WY,Coronavirus Disease 2019,COVID-19,U071,45-54,0,Counts less than 10 suppressed.,4
12024,WY,Coronavirus Disease 2019,COVID-19,U071,55-64,0,Counts less than 10 suppressed.,5
12025,WY,Coronavirus Disease 2019,COVID-19,U071,65-74,0,Counts less than 10 suppressed.,6
12026,WY,Coronavirus Disease 2019,COVID-19,U071,75-84,0,Counts less than 10 suppressed.,7
12027,WY,Coronavirus Disease 2019,COVID-19,U071,85+,0,Counts less than 10 suppressed.,8

In [101]:
data.drop(columns=['Flag','Age Group'], inplace=True)

/tmp/ipython-input-288128839.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(columns=['Flag','Age Group'], inplace=True)

In [102]:
state_counts = data['State'].value_counts()

rare_states = state_counts[state_counts < 50].index

data['State'] = data['State'].replace(rare_states, 'Other')

/tmp/ipython-input-3885856646.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['State'] = data['State'].replace(rare_states, 'Other')

In [103]:
!pip install category_encoders
from category_encoders import TargetEncoder
data['Deaths_log'] = np.log1p(data['Number of COVID-19 Deaths'])
y = data['Deaths_log']

cat_cols = ['State','Condition','ICD10_codes','Condition Group']
te = TargetEncoder(cols=cat_cols)

data[cat_cols] = te.fit_transform(
    data[cat_cols],
    y
)

Requirement already satisfied: category_encoders in /usr/local/lib/python3.12/dist-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)

/tmp/ipython-input-4159088881.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Deaths_log'] = np.log1p(data['Number of COVID-19 Deaths'])
/tmp/ipython-input-4159088881.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[cat_cols] = te.fit_transform(

In [104]:
from sklearn.model_selection import train_test_split


X = data.drop(['Number of COVID-19 Deaths','Deaths_log'], axis=1)
y = data['Deaths_log']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

te = TargetEncoder(cols=cat_cols)

X_train[cat_cols] = te.fit_transform(X_train[cat_cols], y_train)
X_test[cat_cols]  = te.transform(X_test[cat_cols])

In [105]:
data

,State,Condition Group,Condition,ICD10_codes,Number of COVID-19 Deaths,Age_encoded,Deaths_log
0,6.444169,1.896763,2.971796,2.971796,122,1,4.812184
1,6.444169,1.896763,2.971796,2.971796,596,2,6.391917
2,6.444169,1.896763,2.971796,2.971796,1521,3,7.327781
3,6.444169,1.896763,2.971796,2.971796,4186,4,8.339740
4,6.444169,1.896763,2.971796,2.971796,10014,5,9.211839
...,...,...,...,...,...,...,...
12023,0.000007,3.829270,3.829270,3.829270,0,4,0.000000
12024,0.000007,3.829270,3.829270,3.829270,0,5,0.000000
12025,0.000007,3.829270,3.829270,3.829270,0,6,0.000000
12026,0.000007,3.829270,3.829270,3.829270,0,7,0.000000
12027,0.000007,3.829270,3.829270,3.829270,0,8,0.000000

In [106]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9624 entries, 0 to 12027
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   State                      9624 non-null   float64
 1   Condition Group            9624 non-null   float64
 2   Condition                  9624 non-null   float64
 3   ICD10_codes                9624 non-null   float64
 4   Number of COVID-19 Deaths  9624 non-null   int64
 5   Age_encoded                9624 non-null   int64
 6   Deaths_log                 9624 non-null   float64
dtypes: float64(5), int64(2)
memory usage: 601.5 KB

In [108]:
data.head()

,State,Condition Group,Condition,ICD10_codes,Number of COVID-19 Deaths,Age_encoded,Deaths_log
0,6.444169,1.896763,2.971796,2.971796,122,1,4.812184
1,6.444169,1.896763,2.971796,2.971796,596,2,6.391917
2,6.444169,1.896763,2.971796,2.971796,1521,3,7.327781
3,6.444169,1.896763,2.971796,2.971796,4186,4,8.339740
4,6.444169,1.896763,2.971796,2.971796,10014,5,9.211839

In [109]:
X = data.drop(['Number of COVID-19 Deaths','Deaths_log'], axis=1)
y = data['Deaths_log']

In [110]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [111]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

model = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    random_state=42
)

model.fit(X_train, y_train)

preds = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE:", rmse)

RMSE: 0.6814120868521814