In [129]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [130]:
data=pd.read_csv("/content/covid.csv")
data

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region,iso_alpha
0,USA,North America,3.311981e+08,5032179,NaN,162804.0,NaN,2576668.0,NaN,2292707.0,18296.0,15194.0,492.0,63139605.0,190640.0,Americas,USA
1,Brazil,South America,2.127107e+08,2917562,NaN,98644.0,NaN,2047660.0,NaN,771258.0,8318.0,13716.0,464.0,13206188.0,62085.0,Americas,BRA
2,India,Asia,1.381345e+09,2025409,NaN,41638.0,NaN,1377384.0,NaN,606387.0,8944.0,1466.0,30.0,22149351.0,16035.0,South-EastAsia,IND
3,Russia,Europe,1.459409e+08,871894,NaN,14606.0,NaN,676357.0,NaN,180931.0,2300.0,5974.0,100.0,29716907.0,203623.0,Europe,RUS
4,South Africa,Africa,5.938157e+07,538184,NaN,9604.0,NaN,387316.0,NaN,141264.0,539.0,9063.0,162.0,3149807.0,53044.0,Africa,ZAF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,Montserrat,North America,4.992000e+03,13,NaN,1.0,NaN,10.0,NaN,2.0,NaN,2604.0,200.0,61.0,12220.0,NaN,MSR
205,Caribbean Netherlands,North America,2.624700e+04,13,NaN,NaN,NaN,7.0,NaN,6.0,NaN,495.0,NaN,424.0,16154.0,NaN,
206,Falkland Islands,South America,3.489000e+03,13,NaN,NaN,NaN,13.0,NaN,0.0,NaN,3726.0,NaN,1816.0,520493.0,NaN,FLK
207,Vatican City,Europe,8.010000e+02,12,NaN,NaN,NaN,12.0,NaN,0.0,NaN,14981.0,NaN,NaN,NaN,Europe,VAT
208,Western Sahara,Africa,5.986820e+05,10,NaN,1.0,NaN,8.0,NaN,1.0,NaN,17.0,2.0,NaN,NaN,Africa,ESH

In [131]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country/Region    209 non-null    object
 1   Continent         208 non-null    object
 2   Population        208 non-null    float64
 3   TotalCases        209 non-null    int64
 4   NewCases          4 non-null      float64
 5   TotalDeaths       188 non-null    float64
 6   NewDeaths         3 non-null      float64
 7   TotalRecovered    205 non-null    float64
 8   NewRecovered      3 non-null      float64
 9   ActiveCases       205 non-null    float64
 10  Serious,Critical  122 non-null    float64
 11  Tot Cases/1M pop  208 non-null    float64
 12  Deaths/1M pop     187 non-null    float64
 13  TotalTests        191 non-null    float64
 14  Tests/1M pop      191 non-null    float64
 15  WHO Region        184 non-null    object
 16  iso_alpha         209 non-null    object
dtypes: float64(12), int64(1), object(4)
memory usage: 27.9+ KB

In [132]:
data.duplicated().sum()

np.int64(0)

In [133]:
data.describe()

,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop
count,2.080000e+02,2.090000e+02,4.000000,188.000000,3.000000,2.050000e+02,3.000000,2.050000e+02,122.000000,208.000000,187.000000,1.910000e+02,191.000000
mean,3.041549e+07,9.171850e+04,1980.500000,3792.590426,300.000000,5.887898e+04,1706.000000,2.766433e+04,534.393443,3196.024038,98.681176,1.402405e+06,83959.366492
std,1.047661e+08,4.325867e+05,3129.611424,15487.184877,451.199512,2.566984e+05,2154.779803,1.746327e+05,2047.518613,5191.986457,174.956862,5.553367e+06,152730.591240
min,8.010000e+02,1.000000e+01,20.000000,1.000000,1.000000,7.000000e+00,42.000000,0.000000e+00,1.000000,3.000000,0.080000,6.100000e+01,4.000000
25%,9.663140e+05,7.120000e+02,27.500000,22.000000,40.500000,3.340000e+02,489.000000,8.600000e+01,3.250000,282.000000,6.000000,2.575200e+04,8956.500000
50%,7.041972e+06,4.491000e+03,656.000000,113.000000,80.000000,2.178000e+03,936.000000,8.990000e+02,27.500000,1015.000000,29.000000,1.357020e+05,32585.000000
75%,2.575614e+07,3.689600e+04,2609.000000,786.000000,449.500000,2.055300e+04,2538.000000,7.124000e+03,160.250000,3841.750000,98.000000,7.576960e+05,92154.500000
max,1.381345e+09,5.032179e+06,6590.000000,162804.000000,819.000000,2.576668e+06,4140.000000,2.292707e+06,18296.000000,39922.000000,1238.000000,6.313960e+07,995282.000000

In [134]:
data.isna().sum()

Country/Region        0
Continent             1
Population            1
TotalCases            0
NewCases            205
TotalDeaths          21
NewDeaths           206
TotalRecovered        4
NewRecovered        206
ActiveCases           4
Serious,Critical     87
Tot Cases/1M pop      1
Deaths/1M pop        22
TotalTests           18
Tests/1M pop         18
WHO Region           25
iso_alpha             0
dtype: int64

In [135]:
data.shape

(209, 17)

In [136]:
num_cols=data.select_dtypes(include='number').columns
cat_cols=data.select_dtypes(include='object').columns

In [137]:
data[num_cols].columns

Index(['Population', 'TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths',
       'TotalRecovered', 'NewRecovered', 'ActiveCases', 'Serious,Critical',
       'Tot Cases/1M pop', 'Deaths/1M pop', 'TotalTests', 'Tests/1M pop'],
      dtype='object')

In [138]:
data[cat_cols].columns

Index(['Country/Region', 'Continent', 'WHO Region', 'iso_alpha'], dtype='object')

In [139]:
for col in num_cols:
    if col in ["NewCases", "NewDeaths", "NewRecovered", "Serious,Critical"]:
        data[col] = data[col].fillna(0)
    else:
        data[col] = data[col].fillna(data[col].median())
data[cat_cols] = data[cat_cols].fillna("Unknown")

In [140]:
data.head()

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region,iso_alpha
0,USA,North America,3.311981e+08,5032179,0.0,162804.0,0.0,2576668.0,0.0,2292707.0,18296.0,15194.0,492.0,63139605.0,190640.0,Americas,USA
1,Brazil,South America,2.127107e+08,2917562,0.0,98644.0,0.0,2047660.0,0.0,771258.0,8318.0,13716.0,464.0,13206188.0,62085.0,Americas,BRA
2,India,Asia,1.381345e+09,2025409,0.0,41638.0,0.0,1377384.0,0.0,606387.0,8944.0,1466.0,30.0,22149351.0,16035.0,South-EastAsia,IND
3,Russia,Europe,1.459409e+08,871894,0.0,14606.0,0.0,676357.0,0.0,180931.0,2300.0,5974.0,100.0,29716907.0,203623.0,Europe,RUS
4,South Africa,Africa,5.938157e+07,538184,0.0,9604.0,0.0,387316.0,0.0,141264.0,539.0,9063.0,162.0,3149807.0,53044.0,Africa,ZAF

In [141]:
data.isna().sum()

Country/Region      0
Continent           0
Population          0
TotalCases          0
NewCases            0
TotalDeaths         0
NewDeaths           0
TotalRecovered      0
NewRecovered        0
ActiveCases         0
Serious,Critical    0
Tot Cases/1M pop    0
Deaths/1M pop       0
TotalTests          0
Tests/1M pop        0
WHO Region          0
iso_alpha           0
dtype: int64

In [142]:
data.drop(
    ["NewCases","NewDeaths","NewRecovered"],
    axis=1,
    inplace=True
)

In [143]:
data.columns = (
    data.columns
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("/", "_")
    .str.replace(",", "")
)

In [144]:
data

,country_region,continent,population,totalcases,totaldeaths,totalrecovered,activecases,seriouscritical,tot_cases_1m_pop,deaths_1m_pop,totaltests,tests_1m_pop,who_region,iso_alpha
0,USA,North America,3.311981e+08,5032179,162804.0,2576668.0,2292707.0,18296.0,15194.0,492.0,63139605.0,190640.0,Americas,USA
1,Brazil,South America,2.127107e+08,2917562,98644.0,2047660.0,771258.0,8318.0,13716.0,464.0,13206188.0,62085.0,Americas,BRA
2,India,Asia,1.381345e+09,2025409,41638.0,1377384.0,606387.0,8944.0,1466.0,30.0,22149351.0,16035.0,South-EastAsia,IND
3,Russia,Europe,1.459409e+08,871894,14606.0,676357.0,180931.0,2300.0,5974.0,100.0,29716907.0,203623.0,Europe,RUS
4,South Africa,Africa,5.938157e+07,538184,9604.0,387316.0,141264.0,539.0,9063.0,162.0,3149807.0,53044.0,Africa,ZAF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,Montserrat,North America,4.992000e+03,13,1.0,10.0,2.0,0.0,2604.0,200.0,61.0,12220.0,Unknown,MSR
205,Caribbean Netherlands,North America,2.624700e+04,13,113.0,7.0,6.0,0.0,495.0,29.0,424.0,16154.0,Unknown,
206,Falkland Islands,South America,3.489000e+03,13,113.0,13.0,0.0,0.0,3726.0,29.0,1816.0,520493.0,Unknown,FLK
207,Vatican City,Europe,8.010000e+02,12,113.0,12.0,0.0,0.0,14981.0,29.0,135702.0,32585.0,Europe,VAT
208,Western Sahara,Africa,5.986820e+05,10,1.0,8.0,1.0,0.0,17.0,2.0,135702.0,32585.0,Africa,ESH

In [145]:
data["population"] = data["population"].astype(int)

In [146]:
data = pd.get_dummies(
    data,
    columns=["continent","who_region"],
    drop_first=True
)

In [147]:
data

,country_region,population,totalcases,totaldeaths,totalrecovered,activecases,seriouscritical,tot_cases_1m_pop,deaths_1m_pop,totaltests,...,continent_Europe,continent_North America,continent_South America,continent_Unknown,who_region_Americas,who_region_EasternMediterranean,who_region_Europe,who_region_South-EastAsia,who_region_Unknown,who_region_WesternPacific
0,USA,331198130,5032179,162804.0,2576668.0,2292707.0,18296.0,15194.0,492.0,63139605.0,...,False,True,False,False,True,False,False,False,False,False
1,Brazil,212710692,2917562,98644.0,2047660.0,771258.0,8318.0,13716.0,464.0,13206188.0,...,False,False,True,False,True,False,False,False,False,False
2,India,1381344997,2025409,41638.0,1377384.0,606387.0,8944.0,1466.0,30.0,22149351.0,...,False,False,False,False,False,False,False,True,False,False
3,Russia,145940924,871894,14606.0,676357.0,180931.0,2300.0,5974.0,100.0,29716907.0,...,True,False,False,False,False,False,True,False,False,False
4,South Africa,59381566,538184,9604.0,387316.0,141264.0,539.0,9063.0,162.0,3149807.0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,Montserrat,4992,13,1.0,10.0,2.0,0.0,2604.0,200.0,61.0,...,False,True,False,False,False,False,False,False,True,False
205,Caribbean Netherlands,26247,13,113.0,7.0,6.0,0.0,495.0,29.0,424.0,...,False,True,False,False,False,False,False,False,True,False
206,Falkland Islands,3489,13,113.0,13.0,0.0,0.0,3726.0,29.0,1816.0,...,False,False,True,False,False,False,False,False,True,False
207,Vatican City,801,12,113.0,12.0,0.0,0.0,14981.0,29.0,135702.0,...,True,False,False,False,False,False,True,False,False,False
208,Western Sahara,598682,10,1.0,8.0,1.0,0.0,17.0,2.0,135702.0,...,False,False,False,False,False,False,False,False,False,False

In [148]:
data['country_region'].value_counts()

country_region
USA                      1
Brazil                   1
India                    1
Russia                   1
South Africa             1
                        ..
Montserrat               1
Caribbean Netherlands    1
Falkland Islands         1
Vatican City             1
Western Sahara           1
Name: count, Length: 209, dtype: int64

In [149]:
data.drop("country_region", axis=1, inplace=True)
data

,population,totalcases,totaldeaths,totalrecovered,activecases,seriouscritical,tot_cases_1m_pop,deaths_1m_pop,totaltests,tests_1m_pop,...,continent_Europe,continent_North America,continent_South America,continent_Unknown,who_region_Americas,who_region_EasternMediterranean,who_region_Europe,who_region_South-EastAsia,who_region_Unknown,who_region_WesternPacific
0,331198130,5032179,162804.0,2576668.0,2292707.0,18296.0,15194.0,492.0,63139605.0,190640.0,...,False,True,False,False,True,False,False,False,False,False
1,212710692,2917562,98644.0,2047660.0,771258.0,8318.0,13716.0,464.0,13206188.0,62085.0,...,False,False,True,False,True,False,False,False,False,False
2,1381344997,2025409,41638.0,1377384.0,606387.0,8944.0,1466.0,30.0,22149351.0,16035.0,...,False,False,False,False,False,False,False,True,False,False
3,145940924,871894,14606.0,676357.0,180931.0,2300.0,5974.0,100.0,29716907.0,203623.0,...,True,False,False,False,False,False,True,False,False,False
4,59381566,538184,9604.0,387316.0,141264.0,539.0,9063.0,162.0,3149807.0,53044.0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,4992,13,1.0,10.0,2.0,0.0,2604.0,200.0,61.0,12220.0,...,False,True,False,False,False,False,False,False,True,False
205,26247,13,113.0,7.0,6.0,0.0,495.0,29.0,424.0,16154.0,...,False,True,False,False,False,False,False,False,True,False
206,3489,13,113.0,13.0,0.0,0.0,3726.0,29.0,1816.0,520493.0,...,False,False,True,False,False,False,False,False,True,False
207,801,12,113.0,12.0,0.0,0.0,14981.0,29.0,135702.0,32585.0,...,True,False,False,False,False,False,True,False,False,False
208,598682,10,1.0,8.0,1.0,0.0,17.0,2.0,135702.0,32585.0,...,False,False,False,False,False,False,False,False,False,False

In [150]:

y = data["totaldeaths"]

X = data.drop("totaldeaths", axis=1)


X = X.select_dtypes(include=["int64","float64","bool"])

print(X.dtypes)

population                           int64
totalcases                           int64
totalrecovered                     float64
activecases                        float64
seriouscritical                    float64
tot_cases_1m_pop                   float64
deaths_1m_pop                      float64
totaltests                         float64
tests_1m_pop                       float64
continent_Asia                        bool
continent_Australia/Oceania           bool
continent_Europe                      bool
continent_North America               bool
continent_South America               bool
continent_Unknown                     bool
who_region_Americas                   bool
who_region_EasternMediterranean       bool
who_region_Europe                     bool
who_region_South-EastAsia             bool
who_region_Unknown                    bool
who_region_WesternPacific             bool
dtype: object

In [151]:

print(X.dtypes)
X.select_dtypes(include="object")

population                           int64
totalcases                           int64
totalrecovered                     float64
activecases                        float64
seriouscritical                    float64
tot_cases_1m_pop                   float64
deaths_1m_pop                      float64
totaltests                         float64
tests_1m_pop                       float64
continent_Asia                        bool
continent_Australia/Oceania           bool
continent_Europe                      bool
continent_North America               bool
continent_South America               bool
continent_Unknown                     bool
who_region_Americas                   bool
who_region_EasternMediterranean       bool
who_region_Europe                     bool
who_region_South-EastAsia             bool
who_region_Unknown                    bool
who_region_WesternPacific             bool
dtype: object

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[209 rows x 0 columns]

In [152]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [153]:
X

array([[ 2.88555565, 11.44816192,  9.92744974, ..., -0.22416792,
        -0.36860489, -0.278064  ],
       [ 1.74926994,  6.54811712,  7.84251024, ..., -0.22416792,
        -0.36860489, -0.278064  ],
       [12.95638595,  4.48079728,  5.20080178, ...,  4.4609416 ,
        -0.36860489, -0.278064  ],
       ...,
       [-0.29057631, -0.21250233, -0.22772711, ..., -0.22416792,
         2.71293199, -0.278064  ],
       [-0.29060209, -0.21250465, -0.22773105, ..., -0.22416792,
        -0.36860489, -0.278064  ],
       [-0.28486845, -0.21250929, -0.22774681, ..., -0.22416792,
        -0.36860489, -0.278064  ]])